export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'  
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'  
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const CLIENT_SET = 'CLIENT_SET'
export const CLIENT_UNSET = 'CLIENT_UNSET'

// GỬI ĐƠN XEM MỨC THAY ĐỔI LƯƠNG
export const GET_WAGE_STORY='GET_WAGE_STORY'
export const GET_WAGE_STORY_SUCCESS='GET_WAGE_STORY_SUCCESS'
export const GET_WAGE_STORY_ERROR='GET_WAGE_STORY_ERROR'

//GỬI ĐƠN XIN ỨNG LƯƠNG
export const CREATE_PAYROL_REQUEST='CREATE_PAYROL_REQUEST'
export const CREATE_PAYROL_REQUEST_SUCCESS='CREATE_PAYROL_REQUEST_SUCCESS'
export const CREATE_PAYROL_REQUEST_ERROR='CREATE_PAYROL_REQUEST_ERROR'

//GỬI ĐƠN XIN NGHỈ CA
export const CREATE_LEAVE_SHIFT_REQUEST='CREATE_LEAVE_SHIFT_REQUEST'
export const CREATE_LEAVE_SHIFT_REQUEST_SUCCESS='CREATE_LEAVE_SHIFT_REQUEST_SUCCESS'
export const CREATE_LEAVE_SHIFT_REQUEST_ERROR='CREATE_LEAVE_SHIFT_REQUEST_ERROR'

//GỬI ĐƠN XIN NGHỈ VIỆC
export const CREATE_LEAVE_REQUEST='CREATE_LEAVE_REQUEST'
export const CREATE_LEAVE_REQUEST_SUCCESS='CREATE_LEAVE_REQUEST_SUCCESS'
export const CREATE_LEAVE_REQUEST_ERROR='CREATE_LEAVE_SHIFT_REQUEST_ERROR'

// GỬI ĐƠN XIN THAY ĐỔI CA
export const CREATE_CHANGE_SHIFT_REQUEST='CREATE_CHANGE_SHIFT_REQUEST'
export const CREATE_CHANGE_SHIFT_REQUEST_SUCCESS='CREATE_CHANGE_SHIFT_REQUEST_SUCCESS'
export const CREATE_CHANGE_SHIFT_REQUEST_ERROR='CREATE_CHANGE_SHIFT_REQUEST_ERROR'

//GỬI ĐƠN PHẢN HỒI
export const CREATE_FEEDBACK_REQUEST='CREATE_FEEDBACK_SHIFT_REQUEST'
export const CREATE_FEEDBACK_REQUEST_SUCCESS='CREATE_FEEDBACK_SHIFT_REQUEST_SUCCESS'
export const CREATE_FEEDBACK_REQUEST_ERROR='CREATE_FEEDBACK_SHIFT_REQUEST_ERROR'

//SHOW THÔNG BÁO
export const GET_NOTIFICATION='GET_NOTIFICATION'
export const GET_NOTIFICATION_SUCCESS='GET_NOTIFICATION_SUCCESS'
export const GET_NOTIFICATION_ERROR='GET_NOTIFICATION_ERROR'

//Lấy dữ liệu ca làm việc

export const GET_SHIFT = 'GET_SHIFT'
export const GET_SHIFT_SUCCESS = 'GET_SHIFT_SUCCESS'
export const GET_SHIFT_ERROR = 'GET_SHIFT_ERROR'
//lấy dữ liệu ca làm việc trong ngày mà nhân viên chưa bị xếp lịch làm
export const GET_SHIFT_IN_DAY = 'GET_SHIFT_IN_DAY'
export const GET_SHIFT_IN_DAY_SUCCESS = 'GET_SHIFT_SUCCESS_IN_DAY'
export const GET_SHIFT_IN_DAY_ERROR = 'GET_SHIFT_IN_DAY_ERROR'
//
export const GET_LEAVE='GET_LEAVE'
export const GET_LEAVE_SUCCESS='GET_LEAVE_SUCCESS'
export const GET_LEAVE_ERROR='GET_LEAVE_ERROR'
//
export const GET_PAYROLL = 'GET_PAYROLL'
export const GET_PAYROLL_SUCCESS = 'GET_PAYROLL_SUCCESS'
export const GET_PAYROLL_ERROR = 'GET_PAYROLL_ERROR'

//
export const GET_LEAVE_SHIFT='GET_LEAVE_SHIFT'
export const GET_LEAVE_SHIFT_SUCCESS='GET_LEAVE_SHIFT_SUCCESS'
export const GET_LEAVE_SHIFT_ERROR='GET_LEAVE_SHIFT_ERROR'
//
export const GET_CHANGE_SHIFT='GET_CHANGE_SHIFT'
export const GET_CHANGE_SHIFT_SUCCESS='GET_CHANGE_SHIFT_SUCCESS'
export const GET_CHANGE_SHIFT_ERROR='GET_CHANGE_SHIFT_ERROR'
//
export const GET_COMMENT='GET_COMMENT'
export const GET_COMMENT_SUCCESS='GET_COMMENT_SUCCESS'
export const GET_COMMENT_ERROR='GET_COMMENT_ERROR'
///
export const POST_COMMENT='POST_COMMENT'
export const POST_COMMENT_SUCCESS='POST_COMMENT_SUCCESS'
export const POST_COMMENT_ERROR='POST_COMMENT_ERROR'
//Update profile
export const UPDATE_PROFILE='UPDATE_PROFILE'
export const UPDATE_PROFILE_SUCCESS='UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR='UPDATE_PROFILE_ERROR'
//láy ngày công thuộc tháng
export const GET_ATTENDANCE='GET_ATTENDANCE'
export const GET_ATTENDANCE_SUCCESS='GET_ATTENDANCE_SUCCESS'
export const GET_ATTENDANCE_ERROR='GET_ATTENDANCE_ERROR'
//lấy ngày lương theo tháng_tiền
export const GET_PAYROLLS='GET_PAYROLLS'
export const GET_PAYROLLS_SUCCESS='GET_PAYROLLS_SUCCESS'
export const GET_PAYROLLS_ERROR='GET_PAYROLLS_ERROR'
//láy toàn bộ ngày công
export const GET_ATTENDANCES='GET_ATTENDANCES'
export const GET_ATTENDANCES_SUCCESS='GET_ATTENDANCES_SUCCESS'
export const GET_ATTENDANCES_ERROR='GET_ATTENDANCES_ERROR'
//lấy tất cả tiền lương
export const GET_PAYROLLSS='GET_PAYROLLSS'
export const GET_PAYROLLSS_SUCCESS='GET_PAYROLLSS_SUCCESS'
export const GET_PAYROLLSS_ERROR='GET_PAYROLLSS_ERROR'
//
export const UPDATE_PASSWORD='UPDATE_PASSWORD'
export const UPDATE_PASSWORD_SUCCESS='UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_ERROR='UPDATE_PASSWORD_ERROR'